// Programa
const programa = {
  cicloId: { type: 'integer' },
  nivelId: { type: 'integer' },
  solicitudId: { type: 'integer' },
  modalidadId: { type: 'integer' },
  plantelId: { type: 'integer' },
  duracionPeriodos: { type: 'string', format: 'date-time' },
  objetivos: { type: 'string' },
  antecedentes: { type: 'string' },
  creditos: { type: 'string' },
  minimoHorasOptativas: { type: 'integer' },
  minimoCreditosOptativas: { type: 'string' },
  vigencia: { type: 'string', format: 'date-time' },
  fechaSurteEfecto: { type: 'string', format: 'date-time' },
  acuerdoRvoe: { type: 'string' },
  nombre: { type: 'string' },
  tipo: { type: 'integer' },
  actualizacion: { type: 'string' },
  seguimientoEgresados: { type: 'string' },
  conveniosVinculacion: { type: 'string' },
  fuentesInformacion: { type: 'string' },
  estudioOfertaDemanda: { type: 'string' },
  lgac: { type: 'string' },
  necesidadProfesional: { type: 'string' },
  necesidadInstitucional: { type: 'string' },
  necesidadSocial: { type: 'string' },
  recursosOperacion: { type: 'string' },
  antecedenteAcademico: { type: 'string' },
  perfilIngresoConocimientos: { type: 'string' },
  perfilIngresoHabilidades: { type: 'string' },
  perfilIngresoActitudes: { type: 'string' },
  perfilEgresoConocimientos: { type: 'string' },
  perfilEgresoHabilidades: { type: 'string' },
  perfilEgresoActitudes: { type: 'string' },
  procesoSeleccion: { type: 'string' },
  mapaCurricular: { type: 'string' },
  flexibilidadCurricular: { type: 'string' },
  objetivoGeneral: { type: 'string' },
  objetivosParticulares: { type: 'string' },
  calificacionMinima: { type: 'integer' },
  calificacionMaxima: { type: 'integer' },
  calificacionAprobatoria: { type: 'integer' },
  calificacionDecimal: { type: 'boolean' },
};

module.exports = { programa };
