const { Ciclo, CicloSchema } = require('./ciclo');
const { Domicilio, DomicilioSchema } = require('./domicilio');
const { Diligencia, DiligenciaSchema } = require('./diligencia');
const { Estado, EstadoSchema } = require('./estado');
const { EstatusSolicitud, EstatusSolicitudSchema } = require('./estatusSolicitud');
const { File, FileSchema } = require('./file');
const { Institucion, InstitucionSchema } = require('./institucion');
const { Modalidad, ModalidadSchema } = require('./modalidad');
const { Municipio, MunicipioSchema } = require('./municipio');
const { Nivel, NivelSchema } = require('./nivel');
const { Pais, PaisSchema } = require('./pais');
const { Persona, PersonaSchema } = require('./persona');
const { Plantel, PlantelSchema } = require('./plantel');
const { Programa, ProgramaSchema } = require('./programa');
const { RatificacionNombre, RatificacionNombreSchema } = require('./ratificacionNombre');
const { Representante, RepresentanteSchema } = require('./representante');
const { Rol, RolSchema } = require('./rol');
const { Solicitud, SolicitudSchema } = require('./solicitud');
const { TipoInmueble, TipoInmuebleSchema } = require('./tipoInmueble');
const { TipoSolicitud, TipoSolicitudSchema } = require('./tipoSolicitud');
const { Usuario, UsuarioSchema } = require('./usuario');

function setupModels(sequelize) {
  Ciclo.init(CicloSchema, Ciclo.config(sequelize));
  Domicilio.init(DomicilioSchema, Domicilio.config(sequelize));
  Diligencia.init(DiligenciaSchema, Diligencia.config(sequelize));
  Estado.init(EstadoSchema, Estado.config(sequelize));
  EstatusSolicitud.init(EstatusSolicitudSchema, EstatusSolicitud.config(sequelize));
  File.init(FileSchema, File.config(sequelize));
  Institucion.init(InstitucionSchema, Institucion.config(sequelize));
  Modalidad.init(ModalidadSchema, Modalidad.config(sequelize));
  Municipio.init(MunicipioSchema, Municipio.config(sequelize));
  Nivel.init(NivelSchema, Nivel.config(sequelize));
  Pais.init(PaisSchema, Pais.config(sequelize));
  Persona.init(PersonaSchema, Persona.config(sequelize));
  Plantel.init(PlantelSchema, Plantel.config(sequelize));
  Programa.init(ProgramaSchema, Programa.config(sequelize));
  RatificacionNombre.init(RatificacionNombreSchema, RatificacionNombre.config(sequelize));
  Representante.init(RepresentanteSchema, Representante.config(sequelize));
  Rol.init(RolSchema, Rol.config(sequelize));
  Solicitud.init(SolicitudSchema, Solicitud.config(sequelize));
  TipoInmueble.init(TipoInmuebleSchema, TipoInmueble.config(sequelize));
  TipoSolicitud.init(TipoSolicitudSchema, TipoSolicitud.config(sequelize));
  Usuario.init(UsuarioSchema, Usuario.config(sequelize));

  Ciclo.associate(sequelize.models);
  Domicilio.associate(sequelize.models);
  Diligencia.associate(sequelize.models);
  Estado.associate(sequelize.models);
  EstatusSolicitud.associate(sequelize.models);
  File.associate(sequelize.models);
  Institucion.associate(sequelize.models);
  Municipio.associate(sequelize.models);
  Modalidad.associate(sequelize.models);
  Nivel.associate(sequelize.models);
  Pais.associate(sequelize.models);
  Persona.associate(sequelize.models);
  Plantel.associate(sequelize.models);
  Programa.associate(sequelize.models);
  RatificacionNombre.associate(sequelize.models);
  Representante.associate(sequelize.models);
  Rol.associate(sequelize.models);
  TipoInmueble.associate(sequelize.models);
  TipoSolicitud.associate(sequelize.models);
  Solicitud.associate(sequelize.models);
  Usuario.associate(sequelize.models);
}

module.exports = setupModels;
